version: '3.9'

services:
  dev-db:
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - PGDATA=/data/postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d nature -U postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nature-app

  dev-code:
    container_name: nature-app-code
    build:
      context: .
      dockerfile: ./Dockerfile
    restart: always
    ports:
      - '4000:8088'
    depends_on:
      dev-db: 
        condition: service_healthy
    networks:
      - nature-app
    volumes:
      - .:/app

networks:
  nature-app:
    name: nature-app
    external: false