version: '3.9'

services:
  dev-db:
    container_name: nature-app-db
    image: postgres
    environment:
      - POSTGRES_USER=${PG_USER}
      - POSTGRES_PASSWORD=${PG_PASSWORD}
      - POSTGRES_DB=${PG_DATABASE}
      - PGDATA=/data/postgres
      - POSTGRES_HOST_AUTH_METHOD=trust
    ports:
      - '3432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d nature app postgres']
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - nature-app-dev

  dev-code:
    container_name: nature-app-code
    image: nature-app-2023
    restart: always
    ports:
      - '4000:8088'
    networks:
      - nature-app-code
    volumes:
      - .:/app
      - ./volumes:/data/postgres

networks:
  nature-app-dev:
    name: nature-app-dev
    external: false
  nature-app-code:
    name: nature-app-code
    external: false
